# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
windowrule = opacity, 1.0, ^(Geometry Dash)$
windowrule = opacity 1,.*

